spring:
  datasource:
    url: jdbc:h2:mem:test_db
    username: dori
    password: 123456
  jpa:
    show-sql: true
    #hibernate:
    properties:
      hibernate.format_sql: true
    #  ddl-auto: create-drop

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
springdoc:
  swagger-ui:
    path: /swagger-ui.html